version: '3'
services:

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
    ports:
      - "8000:8000" # Proxy
      - "8443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API SSL
    volumes:
      - ./kongConf:/etc/kong
    networks:
      - kong-net


  docs:
    build: ./docs
    networks:
      - kong-net

  users-database:
    image: postgres:16.2
    container_name: ${USERS_DB_HOST}
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASS}
      POSTGRES_DB: ${USERS_DB_NAME}
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - users-net

  user-manage:
    build: ./user_manage
    container_name: user_manager
    environment:
      DB_HOST: ${USERS_DB_HOST} 
      DB_USER: ${USERS_DB_USER}
      DB_PASS: ${USERS_DB_PASS}
      DB_NAME: ${USERS_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - users-database
    networks:
      - users-net
      - kong-net

  game-process:
    build: ./game_process
    container_name: game_process
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
  users-net:
    driver: bridge

volumes:
  users-db-data:
  lobby-db-data:


