version: '3.8'
services:

  kong-database:
    image: postgres:16.2
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
      KONG_PROXY_LISTEN: '0.0.0.0:8000, 0.0.0.0:8443 ssl'
    ports:
      - "8000:8000" # Proxy
      - "443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API SSL
    depends_on:
      - kong-database
    networks:
      - kong-net


  docs:
    image: nikitavoitik/backend-docs:latest
    networks:
      - kong-net

  users-database:
    image: postgres:16.2
    container_name: ${USERS_DB_HOST}
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASS}
      POSTGRES_DB: ${USERS_DB_NAME}
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - users-net

  user-manage:
    image: nikitavoitik/backend-user-manage:latest
    container_name: user_manager
    environment:
      DB_HOST: ${USERS_DB_HOST}
      DB_USER: ${USERS_DB_USER}
      DB_PASS: ${USERS_DB_PASS}
      DB_NAME: ${USERS_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - users-database
    networks:
      - users-net
      - kong-net

  stats-mongodb:
    image: mongo:latest
    container_name: stats-rabbit-mongodb
    hostname: mongodb-host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - stats-rabbit-mongodb-data:/data/db
    networks:
      - stats-net

  stats:
    build: stats-rabbit
    container_name: stats-rabbit
    networks:
      - kong-net
      - stats-net

  game-process:
    image: nikitavoitik/backend-game-process:latest
    container_name: game_process
    networks:
      - kong-net

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: 'rabbitmq'
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    depends_on:
      - stats
      - stats-mongodb
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
  users-net:
    driver: bridge
  stats-net:
    driver: bridge

volumes:
  kong-db-data:
  users-db-data:
  lobby-db-data:
  stats-mongodb-data:

