version: '3'
services:
  kong-database:
    image: postgres:16.2
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    ports:
      - "8000:8000" # Proxy
      - "8443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API SSL
    depends_on:
      - kong-database
    networks:
      - kong-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq
      - rabbit-mq-logs:/var/log/rabbitmq
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - kong-net

  docs:
    build: ./docs
    networks:
      - kong-net

  python-service:
    build: ./python_micro
    networks:
      - kong-net

  node-service:
    build: ./node_serv
    networks:
      - kong-net

  users-database:
    image: postgres:16.2
    container_name: users-database
    environment:
      POSTGRES_USER: users_service
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - users-net

  user-manage:
    build: ./user_manage
    container_name: user_manager
    environment:
      DB_HOST: users-database
      DB_USER: users_service
      DB_PASS: users_password
      DB_NAME: users_db
    depends_on:
      - users-database
    networks:
      - users-net
      - kong-net

networks:
  kong-net:
    driver: bridge
  users-net:
    driver: bridge

volumes:
  kong-db-data:
  rabbit-mq-data:
  rabbit-mq-logs:
  users-db-data:
